#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

CONF_RO_DIR="/usr/share/phosphor-gpio-monitor"
GPIO_CONF_DEFAULT="${CONF_RO_DIR}/phosphor-multi-gpio-monitor.json"
GPIO_CONF_LINK="/var/lib/phosphor-gpio-monitor/phosphor-multi-gpio-monitor.json"

host_os_status_init() {
  local status

  if [ "$(get_gpio FM_BIOS_POST_CMPLT_N)" -eq 0 ]; then
      status="Standby"
  else
      status="Inactive"
  fi

  busctl set-property \
      xyz.openbmc_project.State.Host0 \
      /xyz/openbmc_project/state/host0 \
      xyz.openbmc_project.State.OperatingSystem.Status \
      OperatingSystemState s \
      "xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.${status}"
}

prepare_config_link() {
    local target="$1"
    local link_name="${GPIO_CONF_LINK}"

    mkdir -p "$(dirname "${link_name}")"
    if [ -L "${link_name}" ] && [ "$(readlink -f "${link_name}")" = "${target}" ]; then
        return 0
    fi

    ln -sf "${target}" "${link_name}"
}

host_os_status_init
prepare_config_link "${GPIO_CONF_DEFAULT}"

exit 0
